eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:wang
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: feng
    password: 123#wang
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: bootwang
mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.serverprovider.mapper.UserDao
server:
  port: 8762



